# N.B. This file is bundled and distributed in the enterprise docker image.
database:
  data_source: "sqlite3:///buildbuddy/buildbuddy.db"
storage:
  ttl_seconds: 2592000 # 30 days
  disk:
    root_directory: "/buildbuddy/blobs/"
  enable_chunked_event_logs: true
cache:
  disk:
    root_directory: "/buildbuddy/cache/"
