name: "release-mac"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Git branch to checkout."
        required: true
        default: "master"
        type: string
      version_tag:
        description: "Version to tag release artifacts."
        required: true
        type: string

jobs:
  build:
    runs-on: macos-13
    if: "!contains(github.event.head_commit.message, 'release skip')"
    steps:
      - name: Configure variables
        id: vars
        run: |
          exit 1

  slack_on_failure:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '#ad1411',
                blocks: [
                  {
                    type: 'section',
                    text: {
                      type: 'mrkdwn',
                      text: '*TEST*'
                    }
                  },
                  {
                    type: 'section',
                    text: {
                      type: 'plain_text',
                      text: `More details: https://github.com/buildbuddy-io/buildbuddy/actions/runs/${{ github.run_id }}`
                    }
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_AUTO_RELEASE_WEBHOOK_URL }}